apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: konstantin@semerker.de
    privateKeySecretRef:
      name: letsencrypt-ssl-cert-private-key
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
